%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(miniclip).
-define(miniclip, true).

-define(miniclip_gpb_version, "4.4.0").

-ifndef('DATA_PB_H').
-define('DATA_PB_H', true).
-record(data,
        {key                    :: iolist(),        % = 1
         value                  :: iolist()         % = 2
        }).
-endif.

-ifndef('SET_REQUEST_PB_H').
-define('SET_REQUEST_PB_H', true).
-record(set_request,
        {req                    :: miniclip:data()  % = 1
        }).
-endif.

-ifndef('SET_RESPONSE_PB_H').
-define('SET_RESPONSE_PB_H', true).
-record(set_response,
        {error                  :: 'ok' | 'internal' | integer() % = 1, enum set_response.error_t
        }).
-endif.

-ifndef('GET_REQUEST_PB_H').
-define('GET_REQUEST_PB_H', true).
-record(get_request,
        {key                    :: iolist()         % = 1
        }).
-endif.

-ifndef('GET_RESPONSE_PB_H').
-define('GET_RESPONSE_PB_H', true).
-record(get_response,
        {error                  :: 'ok' | 'not_found' | 'internal' | integer(), % = 1, enum get_response.error_t
         req                    :: miniclip:data() | undefined % = 2
        }).
-endif.

-ifndef('REQ_ENVELOPE_PB_H').
-define('REQ_ENVELOPE_PB_H', true).
-record(req_envelope,
        {type                   :: 'set_request_t' | 'set_response_t' | 'get_request_t' | 'get_response_t' | integer(), % = 1, enum req_envelope.msg_type
         set_req                :: miniclip:set_request() | undefined, % = 2
         set_resp               :: miniclip:set_response() | undefined, % = 3
         get_req                :: miniclip:get_request() | undefined, % = 4
         get_resp               :: miniclip:get_response() | undefined % = 5
        }).
-endif.

-endif.
